### ISSUE TITLE
code availability 

### ISSUE THREAD

**Issue by lisa676** [Jeff-sjtu/HybrIK#1]
Waiting eagerly for this cool stuff

**Comment by Jeff-sjtu** [comment]
Hi Lisa,

Thanks for your interest in our work!
We are working on organizing the code. The code will be released before the Chinese New Year.

Best,
Jeff

**Comment by Jeff-sjtu** [comment]
Hi Lisa @lisa676,

Our code is available now! The pre-trained models and parsed annotations will be coming later. Thanks for your interest. If you have any question or suggestion, do not hesitate to contact us.

Best,
Jeff
