### ISSUE TITLE
about using the twist angle 

### ISSUE THREAD

**Issue by llpspark** [Jeff-sjtu/HybrIK#119]
great work for 3D human. And I wonder to know where it is a mistake about using the twist angle code:https://github.com/Jeff-sjtu/HybrIK/blob/e62363c192b370fc671d2e289c338acda0c0c8c7/hybrik/models/layers/smpl/lbs.py#L742
why using i-1 to index the phis and not using i ?

**Comment by Jeff-sjtu** [comment]
Hi @llpspark, that's because we don't predict the twist angle for the root joint. Thus all indices should subtract 1.

**Comment by llpspark** [comment]
@Jeff-sjtu I'm very glad to communicate with you again here. got it. Because the root node has three child nodes, the unique twist cannot be obtained. 
close it.
