### ISSUE TITLE
Weird pose from smpl mesh and error between pred_xyz_jts_24(3D Pose) and pred_xyz_jts_24_struct(smpl pose)

### ISSUE THREAD

**Issue by liuyuemaicha** [Jeff-sjtu/HybrIK#12]
Hello，Thanks for your great job. When I run your validate_smpl.py with your pretrained model(pretrained_res34.pth) in 3DPW_test_new.json, I found some issues.
1.  The model generate weird pose occasionally，especially the pose from hand and head.
2. There are errors between pred_xyz_jts_24(3D Pose) and pred_xyz_jts_24_struct(smpl pose).
    As we all know, we compute rotation matrix from pred_xyz_jts_24, and compute pred_xyz_jts_24_struct from rotation matrix with smpl. but they are all ways not same, especially on hand and feet.

The images shown in [Weird-pose-from-HybrIK](https://github.com/liuyuemaicha/Weird-pose-from-HybrIK)

Can you help me how to solve above problems ?
Thanks your great jobs again !

**Comment by Jeff-sjtu** [comment]
Hi, I think these problems are caused by inaccurate 3D keypoint estimation. Maybe a stronger backbone or 3D pose estimator is needed.

**Comment by Jeff-sjtu** [comment]
no response, close
