### ISSUE TITLE
Some quetions about the details of 'def batch_get_pelvis_orient_svd'.

### ISSUE THREAD

**Issue by sean-001** [Jeff-sjtu/HybrIK#122]
Hi, thanks for your codes！

I get some puzzles about the implemention of get the global root rotation R0 using SVD.

```python
# rot_mat_non_zero = torch.bmm(V, U.transpose(1, 2))
det_u_v = torch.det(torch.bmm(V, U.transpose(1, 2)))
det_modify_mat = torch.eye(3, device=U.device).unsqueeze(0).expand(U.shape[0], -1, -1).clone()
det_modify_mat[:, 2, 2] = det_u_v
rot_mat_non_zero = torch.bmm(torch.bmm(V, det_modify_mat), U.transpose(1, 2))
```

What is the det_modify_mat and why should we use det_modify_mat instead of rot_mat_non_zero?

**Comment by flybigpig1999** [comment]
this problem may be can solved in this paper 《Least-Squares Fitting of Two 3-D Point Sets》，det_modify_mat  is the factor that make the results of SVD correct in the one condition of calculation，and the result may be wrong in some conditon if not use det_modify_mat .

**Comment by sean-001** [comment]
> this problem may be can solved in this paper 《Least-Squares Fitting of Two 3-D Point Sets》，det_modify_mat is the factor that make the results of SVD correct in the one condition of calculation，and the result may be wrong in some conditon if not use det_modify_mat .

Oh, thanks for your reply !
