### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by mgholamikn** [Jeff-sjtu/HybrIK#123]
Hi Jiefeng,

Thanks a lot for sharing your code. I was wondering if you could share the pretrained model with cam without 3DPW? 

Thanks

**Comment by Jeff-sjtu** [comment]
Hi @mgholamikn, I will release the model in a few days.

**Comment by mgholamikn** [comment]
Thanks a lot Jiefeng, it will help a lot!

**Comment by Jeff-sjtu** [comment]
Hi @mgholamikn, links to pretrained models are updated in README.

**Comment by mgholamikn** [comment]
Thanks a lot @Jeff-sjtu , it truly help future works.
