### ISSUE TITLE
train loss don't converge

### ISSUE THREAD

**Issue by cbyzju** [Jeff-sjtu/HybrIK#126]
![image](https://user-images.githubusercontent.com/13404112/202958431-88bc0b86-7473-4987-95e9-f5abed92ec1c.png)

I use resnet34 as the backbone, after epoch 40, the train loss becomes very large, and don't converge in the remained epoches.

**Comment by Jeff-sjtu** [comment]
Hi @cbyzju, I have fixed the training code. You can try it again.

**Comment by cbyzju** [comment]
> Hi @cbyzju, I have fixed the training code. You can try it again.

Thank you for your quick reply! after removing robust train strategy, model could converge normally. Moreover, I found you add 3d joint regression paradigm with weighted_laplace_loss, is it possible to use RLE loss to get better regression result during train stage?

**Comment by Jeff-sjtu** [comment]
> Thank you for your quick reply! after removing robust train strategy, model could converge normally. Moreover, I found you add 3d joint regression paradigm with weighted_laplace_loss, is it possible to use RLE loss to get better regression result during train stage?

Yes, I am working on it.
