### ISSUE TITLE
why comment loss_xyz during train stage?

### ISSUE THREAD

**Issue by cbyzju** [Jeff-sjtu/HybrIK#128]
https://github.com/Jeff-sjtu/HybrIK/blob/main/hybrik/models/criterion.py#L223

I think it's important to supervise joints in camera coordinate during train stage, but I found you comment loss_xyz, this is confusing to me.

**Comment by biansy000** [comment]
We can implicitly supervise xyz by directly supervising uvd and camera, and in experiments, we find that directly supervising xyz sometimes harms the prediction of camera.

**Comment by cbyzju** [comment]
> 

Got it, Thank you for your kind reply！
