### ISSUE TITLE
test image name

### ISSUE THREAD

**Issue by sarahxinxi** [Jeff-sjtu/HybrIK#13]
I want to use H36m datasets for evaluation, but with the error "FileNotFoundError: [Errno 2] No such file or directory: './data/h36m/images/s_09_act_09_subact_01_ca_04/s_09_act_09_subact_01_ca_04_001756.jpg'". The name of image in S9 subject of H36m is 
![image](https://user-images.githubusercontent.com/35719221/117943031-4d3b2c80-b33e-11eb-936c-7c72c7c143ba.png)
I want to know "s_09_act_09_subact_01_ca_04/s_09_act_09_subact_01_ca_04_001756.jpg" is which one in S9 subject.

**Comment by Jeff-sjtu** [comment]
Hi, we use the images processed in [PoseNet](https://github.com/mks0601/3DMPPE_POSENET_RELEASE). You can download the parsed images from [here](https://drive.google.com/drive/folders/1kgVH-GugrLoc9XyvP6nRoaFpw3TmM5xK?usp=sharing).

**Comment by Jeff-sjtu** [comment]
no response, close
