### ISSUE TITLE
Blender addon not working without camera _prediction

### ISSUE THREAD

**Issue by oscarfossey** [Jeff-sjtu/HybrIK#134]
Thanks for the great repo! 
Importing a non-empty pickle in blender with the add on result into a static animation with only the root animated and fixed at zero.
`KeyError: 'bpy_prop_collection[key]: key "Camera" not found'`

How to import a pickle that does not have camera prediction?

**Comment by Jeff-sjtu** [comment]
Hi @oscarfossey, which version of blender are you using?

**Comment by oscarfossey** [comment]
_" My version of the HybrIk model did not have Camera estimation I think."_  **It has nothing to do with camera estimation** just that the addon want to place a blender camera oriented at the animation. You just have to ensure that a camera is in the blender scene when you importing with the addon.
