### ISSUE TITLE
Size mismatch in function lbs

### ISSUE THREAD

**Issue by Bingrong89** [Jeff-sjtu/HybrIK#136]
Hello, I am attempting to run the validation, but am currently stuck at a problem.
The command i am running is _./scripts/validate_smpl_cam.sh ./configs/256x192_adam_lr1e-3-hrw48_cam_2x_w_pw3d_3dhp.yaml ./pretrained_hrnet.pth_
![image](https://user-images.githubusercontent.com/43532121/207803652-8e5196e5-a2ef-4200-b017-f2a00d855b60.png)
![image](https://user-images.githubusercontent.com/43532121/207801431-016e1882-47ab-4812-8f6c-4265bb5343d8.png)
pose_feature stems from the annotation file, under pw3d.py line 229, theta = np.array(ann['smpl_param']['pose']).reshape(24, 3).  This comes from reading the db.anns['smpl_param']['pose'], under pw3d.py, which returns a length 72 vector, which is transformed to a length 216 vector in simple_transform_3d_smpl_cam.py at theta_rot_mat = batch_rodrigues_numpy(theta).reshape(24 * 9)

This theta is then fed into gt_output = m.module.forward_gt_theta(gt_thetas, gt_betas) in validate_smpl_cam.py
Within that function, gt_thetas is sent to the function lbs, as a size (batchsize,216) torch tensor. 

Then,             rot_mats = batch_rodrigues(pose.view(-1, 3), dtype=dtype).view([batchsize, -1, 3, 3]) transforms it into a shape( batchsize,72,3,3) torch tensor.
Thus, pose_feature = (rot_mats[:, 1:, :, :] - ident).view([batch_size, -1]) , is a shape (batchsize, 71, 3, 3) -> shape (batchsize,639) tensor.
In the next line, pose_offsets = torch.matmul(pose_feature, posedirs).view(batch_size, -1, 3), posedirs is a (207,20670) torch tensor.

Thus, attempting to multiply a (N, 639) matrix with a (207,20670) matrix results in an invalid operation.
As far as I can tell, everything seems to be running as intended and I have downloaded the annotation files as given in this repo.
Can anyone tell me what exactly should be the intended tensor shapes for the input arguments at torch.matmul(pose_feature, posedirs), in lbs.py?

**Comment by Dipankar1997161** [comment]
> Sorry, issue already solved, nothing much.

hey @Bingrong89 , did you got the tensor error like this?

    File "/home/ndip/HybrIK/hybrik/models/layers/smpl/lbs.py", line 874, in batch_inverse_kinematics_transform_naive
        rot_mat_chain[:, indices] = torch.matmul(
    RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1

can you tell me how to solve this.. I need help
