### ISSUE TITLE
关于opencv的版本

### ISSUE THREAD

**Issue by jasonbarthes** [Jeff-sjtu/HybrIK#146]
你好，我在非root用户时进行最后一步pip install -e .
他提示我说errno 13 permission denied
于是我进入root，然后再pip install -e .
报错说无法找到满足requirement的opencv-python==4.1.2.30
如图
![微信图片_20230216001549](https://user-images.githubusercontent.com/101108329/219086826-f9f66c7b-44c5-4e08-b1ce-489340eb43db.png)
请问有什么解决办法吗

**Comment by 15897811771** [comment]
你是按照作者给的方法一步一步进行安装的吗，可能和pytorch、python这些包的版本有关，记得我没有遇到过这个问题。要不你装一下opencv==3.4.10.37看看，我在另一个项目遇到了类似的问题，装这个版本可以正常运行

**Comment by jasonbarthes** [comment]
> 你是按照作者给的方法一步一步进行安装的吗，可能和pytorch、python这些包的版本有关，记得我没有遇到过这个问题。要不你装一下opencv==3.4.10.37看看，我在另一个项目遇到了类似的问题，装这个版本可以正常运行

已经解决了，确实是之前cuda装高了装不了4.1.2.30,。感谢解答
