### ISSUE TITLE
Torch size mismatch error

### ISSUE THREAD

**Issue by wzhang017** [Jeff-sjtu/HybrIK#15]
Hi I see the following error msg when I was running evaluation script. I have placed basicModel_neutral_lbs_10_207_0_v1.0.0.pkl in specified location. Any suggestions? Thanks

 File "D:\HybrIK\scripts\validate_smpl.py", line 216, in main_worker
    m.load_state_dict(torch.load(opt.checkpoint, map_location='cpu'), strict=False)
  File "C:\Users\wzhang2\Miniconda3\envs\hybrik\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Simple3DPoseBaseSMPL:
        size mismatch for final_layer.weight: copying a param with shape torch.Size([1536, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1856, 256, 1, 1]).
        size mismatch for final_layer.bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([1856]).
        size mismatch for smpl.children_map: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([29]).
        size mismatch for smpl.parents: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([29]).

**Comment by wzhang017** [comment]
Problem solved

**Comment by pixelite1201** [comment]
Can you tell how you solve it? I am also getting similar error.
