### ISSUE TITLE
SMPL model not found

### ISSUE THREAD

**Issue by sunwenzhang1996** [Jeff-sjtu/HybrIK#17]
Hello, I only found basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl in the webpage you listed. There is no neutral model for v1.1.0. Can you share this file?

**Comment by Jeff-sjtu** [comment]
Hi, it seems a new version of SMPL is provided. I think this new version also works for our model. You can directly use the v1.1.0 model.

**Comment by sunwenzhang1996** [comment]
Thanks，i will give it a shot

**Comment by wanzysky** [comment]
The `shapedirs` of basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl is 300 while the pre-trained model's is 10, which causes size mismatch when loading the provided model.
