### ISSUE TITLE
About numerical stability

### ISSUE THREAD

**Issue by Woolseyyy** [Jeff-sjtu/HybrIK#2]
Hi! Thank you for your great work!
I am trying to implement your paper before and meet some problem about numerical stability. 
When using svd to compute the rotation matrix of root joint, it may produce matrix whose det is -1 because of the error of predicted pose. Due to the error of the predicted pose, the three joints, spine, left hip and right hip, is not a rigid bod part.
In this case, the optimal matrix is not a rotation matrix but a matrix containing mirror transform.
Hence, when I change this rotation matrix to angle, NaN is produced.
Are there any suggestions?

**Comment by Jeff-sjtu** [comment]
Hi,
Thanks for your interest in our work!

When you say "change this rotation matrix to angle, NaN is produced", I do not understand how you implement it. I just fix some bugs in our implementation of solving the root rotation with SVD. 9cabf52d908418bdb00dee999e67debc738ce79a
Further, we provide another method to solve the root rotation in https://github.com/Jeff-sjtu/HybrIK/blob/9cabf52d908418bdb00dee999e67debc738ce79a/hybrik/models/layers/smpl/lbs.py#L730

I hope this can resolve your concern.

Thanks,
Jeff
