### ISSUE TITLE
Custom Data Training for HybriK Clarification

### ISSUE THREAD

**Issue by Dipankar1997161** [Jeff-sjtu/HybrIK#203]
@wangzheallen, @Jeff-sjtu Thanks for the work. I have a simple query which I wish to ask. 

<img width="800" alt="Screenshot 2023-10-21 at 01 25 23" src="https://github.com/Jeff-sjtu/HybrIK/assets/85514219/5661b683-ef9a-426c-8a7b-1c3c03105347">

In the following file attached above, there are Train_SET and TEST_set mentioned. 

Q1. I have my own dataset which is similar to the size of H36m and has SMPL, 3d and 2d points, do I still need to download all the datasets mentioned in the configs?  I wish to train HybriK from scratch, so any help would be appreciated.

Q.2 While preparing the Train set, which all data is needed? SMPL, 3D joints, 2D joints, Camera Values??  If you can clarify this a bit, it would be much helpful.

Thank you once again

**Comment by sshable** [comment]
Hi Dipankar,

I am also trying to trian hybrIK with a custom 2D datatset.
I wanted to know if you were able to train it with your custom dataset and how?
