### ISSUE TITLE
my training is stuck in training phase

### ISSUE THREAD

**Issue by m-usamasaleem** [Jeff-sjtu/HybrIK#211]
![Screenshot from 2023-11-13 20-53-57](https://github.com/Jeff-sjtu/HybrIK/assets/43682862/acfc9ef3-1682-402a-880a-f1a753f3395b)

Thankyou so much for your repo. I really like it. However, I'm encountering a challenge where the training process seems to halt and doesn't progress beyond a certain point. I'm not entirely sure what could be causing this issue. 

Basically it remain stucks on iterating the **train_loader**.

Would you be able to offer some guidance or advice on how to troubleshoot and resolve this problem?

**Comment by biansy000** [comment]
You may try changing ``cfg.TRAIN.WORLD_SIZE`` to the actual number of GPUs used.
