### ISSUE TITLE
demo 的运行结果

### ISSUE THREAD

**Issue by Qiuxsi** [Jeff-sjtu/HybrIK#216]
无论是 SMPL 还是 SMPL-X，在运行 demo 时得到的 mesh 结果和人物有偏移是正常情况吗（比如下图这种情况）
![000000581667](https://github.com/Jeff-sjtu/HybrIK/assets/71755484/20ad765f-eb87-4447-8682-d6bd3ad8f743)

**Comment by biansy000** [comment]
I think it is strange... But it is hard to debug unless you provide more information.

**Comment by Qiuxsi** [comment]
没事，找到原因了：pytorch3d 的版本太低了！
重新装了环境就能正常使用了~
