### ISSUE TITLE
The `shapedirs` of basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl is 300 while the pre-trained model's is 10, which causes size mismatch when loading the provided model.

### ISSUE THREAD

**Issue by wanzysky** [Jeff-sjtu/HybrIK#24]
The `shapedirs` of basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl is 300 while the pre-trained model's is 10, which causes size mismatch when loading the provided model.

_Originally posted by @wanzysky in https://github.com/Jeff-sjtu/HybrIK/issues/17#issuecomment-872872257_

There is only 1.10 available on the SMPL website, can you please provide the 1.00 version to replicate the results?

**Comment by wanzysky** [comment]
size mismatch for smpl.shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).

**Comment by wanzysky** [comment]
https://github.com/mkocabas/VIBE gives the 1.0.0 model.

**Comment by Jeff-sjtu** [comment]
Hi @wanzysky ,

Did the 1.0.0 model from VIBE works for you? I am not sure if I provide the SMPL 1.0.0 model will violate the license or not.

**Comment by wanzysky** [comment]
> Hi @wanzysky ,
> 
> Did the 1.0.0 model from VIBE works for you? I am not sure if I provide the SMPL 1.0.0 model will violate the license or not.

Yes.

**Comment by julienguegan** [comment]
Hi @wanzysky, I am not sure what needed to be changed here ... In the demo file, I have 
```
cfg_file = 'configs/256x192_adam_lr1e-3-hrw48_cam_2x_w_pw3d_3dhp.yaml'
CKPT = './pretrained_hrnet.pth'
```
In the directory **model_files**, I have all sort of *basicmodel* (1.0.0 and 1.1.0) but I am not sure what to change here ... Thank you for your help !
