### ISSUE TITLE
single_rotation_matrix_to_quaternion_torch may cause wrong tensor device when training with cuda

### ISSUE THREAD

**Issue by wanzysky** [Jeff-sjtu/HybrIK#27]
https://github.com/Jeff-sjtu/HybrIK/blob/16685672fdd3ae7fa86dd570b6d9a56bdbe7a085/hybrik/models/layers/smpl/lbs.py#L959

should explicitly specify the device of the new tensor, or it may result in a CPU tensor.

`return torch.tensor([w, x, y, z], device=rotation_matrix.device).unsqueeze_(0)`

**Comment by Jeff-sjtu** [comment]
Hi, the device of `x`, `y`, `z` and `w` will be consistent with the input `rotation_matrix`. If your input is a GPU tensor, the output will be a GPU tensor.

**Comment by wanzysky** [comment]
Yes, the scalars x to z are GPU tensors, while the tensor constructed by `torch.tensor` will follow the default type.
![image](https://user-images.githubusercontent.com/7082425/124723842-0765a380-df3e-11eb-84e3-9b2017503415.png)

**Comment by Jeff-sjtu** [comment]
Sorry again. This bug is introduced in the last Pull Request. I fix it in 929d90692f4a0b0ccbfc82fa3436736439580c85. Using the `stack` operation seems won't induce the device problem.
