### ISSUE TITLE
Missing Test Model ?

### ISSUE THREAD

**Issue by Minotaur-CN** [Jeff-sjtu/HybrIK#3]
hi Dr.
Missing model for test?
when i using following code to eval.
./scripts/validate_smpl.sh ./configs/256x192_adam_lr1e-3-res34_smpl_3d_base_2x_mix.yaml
Where to download the model for eval?

Thanks

**Comment by Jeff-sjtu** [comment]
Hi,

Thanks for your interest in our work!
Currently, our pre-trained model is not released yet. The pre-trained model and the parsed data annotations will be released together in two weeks.

Best,
Jeff

**Comment by Jeff-sjtu** [comment]
Hi, the pretrained model is uploaded now! Thanks for your interest.
