### ISSUE TITLE
Question about 'Sample_20_test_Human36M_smpl'

### ISSUE THREAD

**Issue by pangbo1997** [Jeff-sjtu/HybrIK#4]
Thank you for your excellent work. 
'Sample_20_test_Human36M_smpl' is required in the project but only 'Sample_64_test_Human36M_protocol_2' found in the given link. Also the given file doesn't include the keys like 'h36m_joints' or 'smpl_joints'. 
Thanks again.

**Comment by Jeff-sjtu** [comment]
Sorry for my mistake. I uploaded the wrong testing file. I have fixed this problem and you can find the correct file now.
Thanks for pointing it out!

**Comment by pangbo1997** [comment]
Thank you for so rapid reply. Uh, the test annotation file of MPI-INF-3DHP is also missing. So could you provide it, too?

**Comment by Jeff-sjtu** [comment]
Hi, I have updated the link for MPI-INF-3DHP dataset. Now you can download the test annotation file.

**Comment by pangbo1997** [comment]
Thanks! Here's my last question, probably. The function 'forward_gt_theta' is missing in the model 'Simple3DPoseBaseSMPL'.

**Comment by Jeff-sjtu** [comment]
Hi, the function 'forward_gt_theta' is deprecated. We use this function only for ablation study. You can just ignore it.

**Comment by pangbo1997** [comment]
For the evaluation of 3DPW, the code in the project tries to recover the mesh of body with the ground truth of shape and theta and then regress to the joint positions. This operation in your code need the function 'forward_gt_theta'.

**Comment by Jeff-sjtu** [comment]
Hi, this bug has fixed now. b8cfeeb7df2d7c8024865751cc17664a8272557b
I hope it works.

**Comment by pangbo1997** [comment]
Thanks and best regards!

**Comment by Jeff-sjtu** [comment]
You're welcome😊
