### ISSUE TITLE
Is it possible to have a demo code?

### ISSUE THREAD

**Issue by KamiCalcium** [Jeff-sjtu/HybrIK#40]
Hi,

Just a suggestion.

I am wondering if it is possible to release a single demo code like 
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/demo/demo.py

Given bbox, root_depth, intrinsic, pre-trained model, and the image, the code will output the keypoints and the rendered mesh. I am working on it right now but it is a little tedious and I cannot be sure that it is totally correct. It will be extremely helpful if you guys can release a official one! 

Thanks!

**Comment by KamiCalcium** [comment]
I'm having some problem when making a full demo code..

I take the Human3.6M dataset as a reference. However, I found that in h36m_smpl.py we have Sample_20_test_Human36M_smpl_protocol_2.json for the smpl data. It is also the same for other datasets, in lazy_load_json(), we always load the .pkl file for the smpl parameters. But for my own dataset, I only have bbox, root_depth, intrinsic, pre-trained model. How can I obtain the smpl parameter from scratch? Which code should I use?

**Comment by KamiCalcium** [comment]
Also, to inference the model, why do we need four input?

```
    result = self.forward(*input, **kwargs)

TypeError: forward() missing 4 required positional arguments: 'trans_inv', 'intrinsic_param', 'joint_root', and 'depth_factor'
```

https://github.com/Jeff-sjtu/HybrIK/blob/c821072e87d20807e662424cc11fe5377c39220e/scripts/validate_smpl.py#L96
Here we can see that we need inps, trans_inv, intrinsic_param, root, depth_factor. Could you please explain what these inputs are?

Again, if I only want to inference, I should only need bbox, root_depth, intrinsic right?

**Comment by KamiCalcium** [comment]
Try to inference my own dataset using the inps, trans_inv, depth_factor, intrinsic_param, and root that I generate, but get this:

```
ModelOutput(pred_shape=<map object at 0x7fd334061f60>, pred_theta_mats=None, pred_phi=None, pred_delta_shape=None, pred_leaf=None, pred_uvd_jts=None, pred_xyz_jts_24=None, pred_xyz_jts_24_struct=None, pred_xyz_jts_17=None, pred_vertices=None, maxvals=None)
```
I only want to get pre_xyz_jts_17. Why is it returning None?

**Comment by KamiCalcium** [comment]
Although output returns None, I somewhat export the pre_xyz_jts_17 before it passed to output. It is like this:
![image](https://user-images.githubusercontent.com/61800479/130334893-02f91d40-9023-467f-a374-1b95aeb1cf9d.png)
I'm a little confused. So the first row is the pelvis index and it is all 0. Does it mean that this coordinate is root-relative? So the pelvis is (0,0,0)? If so, how can I get the coordinate in the cam system or the img system?

**Comment by Jeff-sjtu** [comment]
Hi @KamiCalcium,

Thanks for your suggestion. We are working on the demo code now, and we also plan to merge this project to [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose).

The `pkl` file is just for fast loading during training. You  can remove them and write a new loading function according to your data format.
> I'm having some problem when making a full demo code..
> 
> I take the Human3.6M dataset as a reference. However, I found that in h36m_smpl.py we have Sample_20_test_Human36M_smpl_protocol_2.json for the smpl data. It is also the same for other datasets, in lazy_load_json(), we always load the .pkl file for the smpl parameters. But for my own dataset, I only have bbox, root_depth, intrinsic, 17 3D keypoints. How can I obtain the smpl parameter from scratch? Which code should I use?

In our implementation, if the translation `transl` is not None, the output of the `hybrik` function add the global translation to the vertices and the joints.  
> Although output returns None, I somewhat export the pre_xyz_jts_17 before it passed to output. It is like this:
> ![image](https://user-images.githubusercontent.com/61800479/130334893-02f91d40-9023-467f-a374-1b95aeb1cf9d.png)
> I'm a little confused. So the first row is the pelvis index and it is all 0. Does it mean that this coordinate is root-relative? So the pelvis is (0,0,0)? If so, how can I get the coordinate in the cam system or the img system?
> 
> Also, if it is already the root-relative coordinates, then what does this do?
> https://github.com/Jeff-sjtu/HybrIK/blob/b8cfeeb7df2d7c8024865751cc17664a8272557b/hybrik/datasets/hp3d.py#L335
> 
> 
> pred_3d_kpt[0] will be all 0, right? It is meaningless to subtract it.

**Comment by KamiCalcium** [comment]
> Hi @KamiCalcium,
> 
> Thanks for your suggestion. We are working on the demo code now, and we also plan to merge this project to [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose).
> 
> The `pkl` file is just for fast loading during training. You can remove them and write a new loading function according to your data format.
> 
> > I'm having some problem when making a full demo code..
> > I take the Human3.6M dataset as a reference. However, I found that in h36m_smpl.py we have Sample_20_test_Human36M_smpl_protocol_2.json for the smpl data. It is also the same for other datasets, in lazy_load_json(), we always load the .pkl file for the smpl parameters. But for my own dataset, I only have bbox, root_depth, intrinsic, 17 3D keypoints. How can I obtain the smpl parameter from scratch? Which code should I use?
> 
> In our implementation, if the translation `transl` is not None, the output of the `hybrik` function add the global translation to the vertices and the joints.
> 
> > Although output returns None, I somewhat export the pre_xyz_jts_17 before it passed to output. It is like this:
> > ![image](https://user-images.githubusercontent.com/61800479/130334893-02f91d40-9023-467f-a374-1b95aeb1cf9d.png)
> > I'm a little confused. So the first row is the pelvis index and it is all 0. Does it mean that this coordinate is root-relative? So the pelvis is (0,0,0)? If so, how can I get the coordinate in the cam system or the img system?
> > Also, if it is already the root-relative coordinates, then what does this do?
> > https://github.com/Jeff-sjtu/HybrIK/blob/b8cfeeb7df2d7c8024865751cc17664a8272557b/hybrik/datasets/hp3d.py#L335
> > 
> > pred_3d_kpt[0] will be all 0, right? It is meaningless to subtract it.

Hi,

Did you try to reply my last question? I didn't see te answer, but only see that you quote it.

**Comment by Jeff-sjtu** [comment]
Hi @KamiCalcium, the [demo code](https://github.com/Jeff-sjtu/HybrIK/blob/main/README.md#quick-start) is now available.
