### ISSUE TITLE
About SMPL gt and H36M gt !!

### ISSUE THREAD

**Issue by Z-Z-J** [Jeff-sjtu/HybrIK#42]
Your json file provides the H36M joint coordinates obtained from the SMPL gt parameters.
But I found that the yours provided joints3D data is different from which given in Human3.6 official site.  
E.g
    
![QQ截图20210902122243](https://user-images.githubusercontent.com/53818279/131781403-6f7ba7b5-ff08-45e6-bce1-b3767208a9c3.png)

![QQ截图20210902122348](https://user-images.githubusercontent.com/53818279/131781479-c744e3ea-a62c-4541-8d98-c098f7be238d.png)

![QQ截图20210902122436](https://user-images.githubusercontent.com/53818279/131781672-b008650b-4d38-4aeb-9795-31166ffa0e8a.png)

**Comment by Z-Z-J** [comment]
> 嗨， H36M 接头是从 SMPL 参数获得的。SMPL 参数通过拖把获得。因此，可能与官方关节略有不同。

Thank you for answering so quickly !  
The generate_json.py you provided does not generate the final json file( Sample_5_train_Human36M_smpl_leaf_twist_protocol_2.json ).
Can you provide me the code for how to generate Sample_5_train_Human36M_smpl_leaf_twist_protocol_2.json ?

**Comment by Jeff-sjtu** [comment]
Hi @Z-Z-J, the generation of the JSON file has several steps. We don't have a single script for the generation. We first obtain the SMPL parameters and joint positions. Then add the extra leaf joints. Finally, we calculate the twist angles (as issue #37).
