### ISSUE TITLE
About the data you provide!

### ISSUE THREAD

**Issue by Z-Z-J** [Jeff-sjtu/HybrIK#43]
Your json file provides thetas, betas, smpl_joints, h36m_joints.
I calculated the smpl joints by thetas, betas and J_regressor(basicModel_neutral_lbs_10_207_0_v1.0.0.pkl), it is the same as the smpl_joints you provided.
     smpl joints - smpl joints root coordinate (I calculated) = smpl_joints - smpl_joints root coordinate (You provide)

But, I calculated the h36m joints by thetas, betas and J_regressor_h36m(from J_regressor_h36m_correct.npy), it is different from the h36m_joints you provided.
     h36m_joints - h36m_joints root coordinate (I calculated) ≠ h36m_joints - h36m_joints root coordinate (You provide)
Why?

**Comment by Jeff-sjtu** [comment]
Hi, it seems the `J_regressor` you used (J_regressor_h36m_correct.npy) is different from the one I used. I think it would cause some difference.
