### ISSUE TITLE
About R and t in h36m

### ISSUE THREAD

**Issue by pangyyyyy** [Jeff-sjtu/HybrIK#46]
Hi, thanks for the great work! 

I have a few questions regarding the data preprocessing:
1. How did you obtain the camera parameters `R`, `t`, `f`, `c` in H36M? I've tried to derive the camera parameters from `metadata.xml` provided in the H36M website but I got a different `t` from the ones in your annotation file. 
2. Would you mind providing the code you use for deriving the camera parameters?

**Comment by Jeff-sjtu** [comment]
Hi @pangyyyyy, I don't have the code to obtain the intrinsic camera parameters in Human3.6M. I just follow the previous open-sourced code.

**Comment by pangyyyyy** [comment]
@Jeff-sjtu , thanks for your reply! Do you mind pointing me to the open-sourced code that you referred to to obtain the h36m extrinsic and intrinsic camera parameters? 

Thanks!

**Comment by Jeff-sjtu** [comment]
> @Jeff-sjtu , thanks for your reply! Do you mind pointing me to the open-sourced code that you referred to to obtain the h36m extrinsic and intrinsic camera parameters?
> 
> Thanks!

Our JSON files are partly developed from [PoseNet](https://github.com/mks0601/3DMPPE_POSENET_RELEASE). If you want to train the monocular model, I think the extrinsic parameters might be not necessary.

**Comment by pangyyyyy** [comment]
I'll check them out. Thanks for your reply!!
