### ISSUE TITLE
How to generate the thetas and betas parameter?

### ISSUE THREAD

**Issue by xinsirBUPT2016** [Jeff-sjtu/HybrIK#5]
Hi, I have download the human3.6m dataset, however, i couldn't find a way to produce the thetas and betas parameter. The only clue we know comes from the SPIN issue, which use the sensors data and Mosh methods to generate theta and beta parameter, but the sensor data of human3.6m and code of Mosh is not public, we are very anxious to generate the pose parameter both in training and testing dataset, can you please answer it?

**Comment by Jeff-sjtu** [comment]
Hi, we provide the annotation files that contain the `theta` and `beta` parameters. These parameters are generated by Mosh. You can directly use our JSON files.

**Comment by xinsirBUPT2016** [comment]
sure, I have see your json data, the theta and beta params are extracted every 5 frames in a video,  but in some cases, we need successive frames to do some expriments and recover some result in human3.6m, so would mind provide some details about the methods and the sensor data?  Is it possible to apply to the human3.6 official to get the sensor data?

**Comment by Jeff-sjtu** [comment]
Do you have the moshed data? I generate the JSON annotations from the moshed results.

**Comment by xinsirBUPT2016** [comment]
what is the format of moshed data,  We get access to the human3.6 dataset，and the pose annotations is a obj file，is it the moshed data? Besides，how do you generate the annotations,  use the mosh methods with the sensor data, or use the SMPL models?

**Comment by Jeff-sjtu** [comment]
The moshed data is download from the open-source code of the previous method a long time ago. I upload the JSON files before downsampling on [Baidu Drive](https://pan.baidu.com/s/1fVMBMQ9kO3gBI2NN_mwJmQ). I hope it would help.

**Comment by xinsirBUPT2016** [comment]
Could you please tell me the extract code in a private way that you are convenient?

**Comment by Jeff-sjtu** [comment]
Hi, the code is `ey7w`.

**Comment by xinsirBUPT2016** [comment]
Hi，is it the total annotation data for human3.6m,  I have download the files, and load the json, however it is still discontinuous,  every 5 frames select 1.  Anyway, thank you for you coco-operation, it is indeed very difficult to find the total pose data for human3.6m. There are a lot of tricks to generate the data and not owned by us, You are a very enthusiastic person, for you kindness reply. Thank you!

**Comment by Jeff-sjtu** [comment]
Hi, I just check the moshed data and the code. I find that the moshed data provide continuous annotations. But the results (e.g. global orientation) maybe not aligned with the camera. I upload it on [Baidu Drive](https://pan.baidu.com/s/18Tcindj2nycaxg5pPjeYyA) (code `k77z`) with the code that used to downsample the results. I hope it can help you!

**Comment by xinsirBUPT2016** [comment]
Thank you very much! It helps us a lot and we can continue our research due to this. You can contact me when you want to find a job or intership,  if you want to go to megvii, sensetime, bytedance, baidu and so on. My email is xinsir@bupt.cn

**Comment by Jeff-sjtu** [comment]
Thanks for your sincerity!

**Comment by JinShiyin** [comment]
Hi, I have downloaded the moshed data and the code, the raw_p['poses'] contains pose params in camera0,1,2,3, however I can't find  the order of camera 0,1,2,3 saved in raw_p['poses'], and how many images in each camera, can you please answer it? Thank you.

**Comment by Jeff-sjtu** [comment]
Hi @JinShiyin, actually I do not use the raw pkl file and only load the poses from the `_aligned.pkl`. It seems the poses in `camx_aligned.pkl` are downsampled by the rate of 5. If you only need the downsampled data, you can directly use the `camx_aligned.pkl`.

**Comment by Frank-Dz** [comment]
> Hi @JinShiyin, actually I do not use the raw pkl file and only load the poses from the `_aligned.pkl`. It seems the poses in `camx_aligned.pkl` are downsampled by the rate of 5. If you only need the downsampled data, you can directly use the `camx_aligned.pkl`.

Hi~ I found the downsampling codes need 
```
import metadata as md 
```
But there is no this file.
Could you share the code here?
Thank you very much!

**Comment by NewCoderQ** [comment]
> 

Hi @Jeff-sjtu , what is the different processing between *.pkl and the *_cam*_aligned.pkl, or could you tell me where I can find the process scripts?

**Comment by NewCoderQ** [comment]
> Hi @JinShiyin, actually I do not use the raw pkl file and only load the poses from the `_aligned.pkl`. It seems the poses in `camx_aligned.pkl` are downsampled by the rate of 5. If you only need the downsampled data, you can directly use the `camx_aligned.pkl`.

Hi @Jeff-sjtu , what is the different processing between *.pkl and the *_camx_aligned.pkl, or could you tell me where I can find the process scripts? I want to get the continuous smpl mesh.

**Comment by moezet01** [comment]
Hi @Jeff-sjtu. 
Congratulations to the authors for this great research work!

I am trying to understand the generation process of 'thetas' and 'betas' parameters of Human3.6m. 
I cannot download the Mosh code from Baidu drive. Is there any other way to see that?
And, does that Mosh method come from that [paper](https://ps.is.mpg.de/publications/loper-sigasia-2014)?
