### ISSUE TITLE
Flip_item is not applied during training

### ISSUE THREAD

**Issue by pangyyyyy** [Jeff-sjtu/HybrIK#55]
Dear authors, thanks for the great work!

I noticed that parameter `flip_item` passed into the model is set to None during `train()` but is popped from `is_flipped` key during `validate_gt()`

In train:
https://github.com/Jeff-sjtu/HybrIK/blob/b8cfeeb7df2d7c8024865751cc17664a8272557b/scripts/train_smpl.py#L57

in validate_gt:
https://github.com/Jeff-sjtu/HybrIK/blob/b8cfeeb7df2d7c8024865751cc17664a8272557b/scripts/train_smpl.py#L128-L130

When `flip_item` is set to`None`, the phi, leaf, shapes and uvd_coordinates will not be flipped during training even though the image and keypoints3d might be flipped during augmentations. 
https://github.com/Jeff-sjtu/HybrIK/blob/e10afb149e10cf721b619b12eb81f02b7ad3c4e0/hybrik/models/simple3dposeBaseSMPL24.py#L298-L325

I would also like to confirm if `flip_item` is indeed set to None for all training? And if yes, why is flipping of phi, shapes and uvd_coord not applied during training, but applied during validation?  

I am rather confused regarding this procedure, and hope to get some clarification on this. Thank you!

**Comment by Jeff-sjtu** [comment]
Hi @pangyyyyy,

During training, the input image and labels are already flipped in the dataloder. Therefore, we do not need to flip again. During testing, we want to improve the accuracy by averaging the results of before and after flip.

**Comment by pangyyyyy** [comment]
@Jeff-sjtu Thanks for the reply! The input image and labels (joints and thetas) are flipped in the dataloader during training, but the `target_twist` and `target_twist_weight` which was generated from twist phi were not flipped

Code for flipping:
https://github.com/Jeff-sjtu/HybrIK/blob/ff6e61d37b521b2730493e9597c37db24ddb356a/hybrik/utils/presets/simple_transform_3d_smpl.py#L398-L409 

Can I check if my understanding of the above procedure is correct?

**Comment by pangyyyyy** [comment]
Hi @Jeff-sjtu any updates on the bug fix?

**Comment by Jeff-sjtu** [comment]
Hi @pangyyyyy, I think the bug is fixed now!

**Comment by pangyyyyy** [comment]
That's great! Thank you so much!
