### ISSUE TITLE
question about Human3.6M dataset.

### ISSUE THREAD

**Issue by Frank-Dz** [Jeff-sjtu/HybrIK#56]
As mentioned in the paper, you are using posenet's h36m dataset. 
And the training process adopts supervision on joint rotation. Are you using the rotation annotated by posenet?

Are you using the **fitted_3d_pose: 17x2 dimensional joint coordinates (in world coordinate system) from the fitted mesh** provided by posenet for evaluation?

Thank you very much!

**Comment by YHDang** [comment]
> As mentioned in the paper, you are using posenet's h36m dataset. And the training process adopts supervision on joint rotation. Are you using the rotation annotated by posenet?
> 
> Are you using the **fitted_3d_pose: 17x2 dimensional joint coordinates (in world coordinate system) from the fitted mesh** provided by posenet for evaluation?
> 
> Thank you very much!

Hello. Did you download the posenet's h36m dataset successfully?
