### ISSUE TITLE
When will you release your test code?

### ISSUE THREAD

**Issue by vigorbird** [Jeff-sjtu/HybrIK#58]
I find that you do not provide demo code to test wild images. When will you release your demo code? 
Without demo code, it is very hard to evalute your algorithm using wild images

**Comment by Jeff-sjtu** [comment]
Hi, we've been really busy lately. We will release the demo code as soon as possible.

**Comment by Jeff-sjtu** [comment]
Hi @vigorbird, the [demo code](https://github.com/Jeff-sjtu/HybrIK/blob/main/README.md#quick-start) is now available.
