### ISSUE TITLE
how to test?

### ISSUE THREAD

**Issue by Lixz123456** [Jeff-sjtu/HybrIK#6]
hi~great job
I want to know how to test with my own data to obtain smpl's  parameter ？

**Comment by Jeff-sjtu** [comment]
Hi, if you want to test with your own data, you need to run object detection to generate human bounding boxes. Then use [RootNet](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) to predict the root joint in each bounding box. Combing box and root joint, you can run our model to predict the final SMPL results.

This is a tedious process. Now we are working at integrating our method into [Alphapose](https://github.com/MVIG-SJTU/AlphaPose). When done, the whole process will be much simpler.

**Comment by leeskyed** [comment]
Any updates about the pre-trained models ><

**Comment by Jeff-sjtu** [comment]
@leeskyed Hi, the pretrained model based on ResNet-34 is uploaded now! Please follow the instructions in README.

**Comment by jinfagang** [comment]
@Jeff-sjtu Hi, how's the intergate into AlphaPose going?
