### ISSUE TITLE
How to apply my own 3d keypoints on HybrIK?

### ISSUE THREAD

**Issue by shaoguowen** [Jeff-sjtu/HybrIK#61]
How to convert my own 3d keypoints in the world  to meet the input data format of HybrIK?

**Comment by Holmes-Alan** [comment]
@shaoguowen have you resolved this problem?

**Comment by Dipankar1997161** [comment]
> @shaoguowen have you resolved this problem?

Hey have you solved this? Or atleast can tell me what's thr input format?
