### ISSUE TITLE
Process to generate the JSON annotation files

### ISSUE THREAD

**Issue by Tina-Husky** [Jeff-sjtu/HybrIK#7]
Hi, HybrIK is indeed an awesome and elegant work. I really like it! Congratulations!

But, there's something I'm curious about, which is the process to generate JSON annotation files from the original datasets.
I would surely appreciate it if you would share some hints about the procedure.

Thanks again.

**Comment by Jeff-sjtu** [comment]
Hi, may this issue can help you. #5 
I provide the code that used to generate the JSON files in [Baidu Drive](https://pan.baidu.com/s/18Tcindj2nycaxg5pPjeYyA) (code `k77z`) along with the original annotations. If Baidu Drive is not available to you, I could upload it to Google Drive.

**Comment by Tina-Husky** [comment]
I really appreciate this! The question has been solved.
