### ISSUE TITLE
Google Colab demo fails at the setup steps...

### ISSUE THREAD

**Issue by bsense-rius** [Jeff-sjtu/HybrIK#72]
Dear Jeff,

First of all thank you so much for sharing this implementation. It looks really impressive.

I just want to report that the google colab notebook does not seem to work. Each time I start it from scratch, fail at:
```
# conda environment setup
!conda create -n hybrik python=3.7
!source activate hybrik && pip install ipython
```
Google Colab session crashes. At pip install ipython.

Can you help me solve that?

**Comment by Jeff-sjtu** [comment]
Hi @bsense-rius, the Colab notebook will automatically restart and you can directly run the next block.

**Comment by bsense-rius** [comment]
Hi!

You are right, Sorry! It might be useful to add a text cell commenting that out, so that dumber people like me, that are unaware of this ipython installation technique overriding colab's default know that is perfectly right to proceed.

Thanks again

**Comment by Jeff-sjtu** [comment]
Thank you very much for your suggestion!
