### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by ykgod7** [Jeff-sjtu/HybrIK#75]
`In file included from opendr/contexts/OSMesa/include/GL/gl.h:2085:0,
                 from opendr/contexts/gl_includes.h:10,
                 from opendr/contexts/ctx_mesa.c:756:
opendr/contexts/OSMesa/include/GL/glext.h:5794:21: note: expected ‘const GLchar ** {aka const char **}’ but argument is of type ‘char **’
 GLAPI void APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar* *string, const GLint *length);
                     ^~~~~~~~~~~~~~
/home/training/anaconda3/envs/hybrik/compiler_compat/ld: cannot find -lOSMesa: No such file or directory
collect2: error: ld returned 1 exit status
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1
`

I got this error while following the installation direction `python setup.py develop`. How can I solve this?

**Comment by Tengoles** [comment]
I have the same problem, some support would be very appreciated.

**Comment by Tengoles** [comment]
Just found the solution by installing the libraries mentioned in the last comment from here: https://github.com/mattloper/opendr/issues/30

**Comment by afiretony** [comment]
I gauss the problem is that we haven't installed osmesa, I solved by `sudo apt-get install libosmesa6-dev`
