### ISSUE TITLE
Questions about annotations of Human3.6M.

### ISSUE THREAD

**Issue by weiwen1990** [Jeff-sjtu/HybrIK#8]
Great Job and thank you for your excellent work.

However, I have some question. Yours provided joints3D data is different from which given in  Human3.6 official site. I have checked  the Positions_D3_positions_mono's file which has also been used in SPIN. So, Is there existing something external operation?

**Comment by Jeff-sjtu** [comment]
Hi, we obtained the 3d joint annotations from the SMPL parameters (using regressor to obtain 17 joints from the mesh). It might be a litter different from the originally labelled joints from Human3.6M.  For the 3DPW data, we use the parsed data provided by [I2L](https://github.com/mks0601/I2L-MeshNet_RELEASE).
