### ISSUE TITLE
About the simple3dposeSMPLWithCam forward

### ISSUE THREAD

**Issue by mingliutju** [Jeff-sjtu/HybrIK#80]
Hi, thanks for your nice work!
I noticed that the pred_xyz_jts_29 was in-bbox coordinate. why not remap to the input space?

**Comment by Jeff-sjtu** [comment]
Hi @mingliutju, it's the same when we perform the inverse kinematics. We remap the coordinates to the image space when we visualize the results.

**Comment by mingliutju** [comment]
Oh, I got it, thank you very much!
