### ISSUE TITLE
The pretrained model link is not available

### ISSUE THREAD

**Issue by wzhang017** [Jeff-sjtu/HybrIK#9]
Could you please re-upload the model again? Thanks

**Comment by Jeff-sjtu** [comment]
Hi, could you download the model from [this link](https://drive.google.com/file/d/1SoVJ3dniVpBi2NkYfa2S8XEv0TGIK26l/view?usp=sharing)?

**Comment by Jeff-sjtu** [comment]
I have reset the permissions of the file.

**Comment by wzhang017** [comment]
I've downloaded it, thanks!!!
