### ISSUE TITLE
Traning with RLE loss

### ISSUE THREAD

**Issue by PGogo** [Jeff-sjtu/HybrIK#91]
Thanks for your great work and sharing your implementation.^^
I noticed that another work "Human Pose Regression with Residual Log-likelihood Estimation" is also one of yours. And it is superior to the heatmap-based methods in a regression manner. I wonder if it still works in HybrIK. And what were the results between heatmap-based methods and regression-based methods in the experiment, of course if you ever gave it a try.

**Comment by Jeff-sjtu** [comment]
Hi @PGogo, thanks for your interest in our work. Actually, we have tried RLE on HybrIK and found the performances (MPJPE) on 3DPW and Human3.6M are similar to the heatmap-based version. But RLE has the potential to defeat the heatmap-based version in the sciences of truncation and occlusion.

**Comment by PGogo** [comment]
Thanks!
